# Replace with your Discord Application ID
application_id: "1311204057490259979"

# Activity type: 0 = Playing, 1 = Streaming, 2 = Listening, 3 = Watching
type: 3

# Activity Details
name: "B.O.R (Birth Of Rap)"
details: "Lil B"
state: "Spotify"

# Activity Images
largeImageKey: "https://i1.sndcdn.com/artworks-000541047288-be0f6i-t500x500.jpg"
largeImageText: "Listening to B.O.R (Birth Of Rap) Lil B"
smallImageKey: "https://static.vecteezy.com/system/resources/previews/023/986/494/non_2x/spotify-logo-spotify-logo-transparent-spotify-icon-transparent-free-free-png.png"
smallImageText: "Spotify"

# Activity URL (optional, works only with certain types)
url: "https://www.youtube.com/@nexoscreator"

# Activity Buttons (optional)
buttons:
  - name: "Listen Along"
    url: "https://open.spotify.com/track/4VGr45NZouCH9cb7JYgvLc"

# Activity Custom status
custom_status: "TYBG"
custom_emoji: "🪽"
